### ISSUE TITLE
Consider adding an open-source license

### ISSUE THREAD

**Issue by pierrebeaucamp** [cryptocode/marble#1]
Hi,

I would love to use your code in a project of mine. However, without an explicit license in this repository, this would constitute a copyright violation.

Please consider adding an open-source license (for example, one of the [OSI-approved licenses](https://opensource.org/licenses)). Github also publishes this guide to choosing a license: https://choosealicense.com

Thank you

**Comment by cryptocode** [comment]
Nearly all my projects are MIT licensed and this repo is no different, file just wasn't added to the repo by mistake. 

Appreciate the ping about this, and I'll push a fix once I get this repo upgraded to Zig 0.13.

EDIT: I'll push the LICENSE file anyway, in case you're on an older Zig version
